adaptlearning/adapt-contrib-boxMenu

less/boxmenu.less, templates/boxmenu-item.hbs, templates/boxmenu.hbs
=> Accessibility merge

example.json
=> Remove redundant aria labels, Fixes issue/#42

templates/boxmenu.hbs
https://adaptlearning.atlassian.net/browse/ABU-867
=> Added aria-label to indicate end of menu.

templates/boxmenu.hbs
Out of date with readMe. title should only be used as a reference and displayTitle render.
=> replace title with displayTitle

properties.schema, templates/boxmenu-item.hbs, templates/boxmenu.hbs
move
_globals._accessibility._ariaLabels.menu
_globals._accessibility._ariaLabels.menuItem
_globals._accessibility._ariaLabels.menuEnd
to
_globals._menu._boxmenu.ariaRegion
_globals._menu._boxmenu.ariaRegionMenuItem
_globals._menu._boxmenu.ariaMenuEndLabel
=> Move global aria labels

templates/boxmenu-item.hbs
* Need to add ``_globals._accessibility._ariaLabels.visited: "visited"`` to course.json
=> ABU-845: Visited element on button aria label

js/adapt-contrib-boxmenu.js, templates/boxmenu-item.hbs
=> a to button

templates/boxmenu-item.hbs
Base class not required on this button
=> Removed base class from button

js/adapt-contrib-boxmenu.js, templates/boxmenu-item.hbs
Also prevents IE9 missing image placeholder.
=> Allows menu item images to be optional.

bower.json, example.json, properties.schema, templates/boxmenu-item.hbs
https://adaptlearning.atlassian.net/browse/ABU-1110
=> Moved durationLabel to _globals

js/adapt-contrib-boxmenu.js
https://github.com/adaptlearning/adapt_framework/issues/880
=> Enhancement/880: Box menu - visited and completed states

.gitignore, js/adapt-contrib-boxmenu.js, templates/boxmenu-item.hbs
- As per https://github.com/adaptlearning/adapt_framework/issues/905
- Removed the `role="button"` attribute
- Removed the `.gitignore` file
=> implemented _isLocked attribute

README.md, bower.json, templates/boxmenu-item.hbs, templates/boxmenu.hbs
added dependency on framework ~2.0.20~ 2.1.0 - which doesn't actually exist yet but will do v. soon!
=> amend templates to allow for handlebars style expressions in the json

templates/boxmenu-item.hbs, templates/boxmenu.hbs
https://github.com/adaptlearning/adapt_framework/issues/833
=> boxMenu - removed references to accessible-text-block

js/adapt-contrib-boxmenu.js, less/boxmenu.less
https://github.com/adaptlearning/adapt_framework/issues/1839
switched to using ``.boxmenu-menu`` instead of ``.menu``
=> issue/1839: made boxmenu styling more specific

README.md, bower.json, example.json, js/adapt-contrib-boxmenu.js
=> add ability to hide pages from the menu

README.md, bower.json, example.json, js/adapt-contrib-boxmenu.js, less/boxmenu.less, templates/boxmenu-item.hbs, templates/boxmenu.hbs
BoxMenu converted to use 2 spaces for indentation.
=> update to use 2 spaces for indentation

bower.json, templates/boxmenu-item.hbs
PR to fix https://github.com/adaptlearning/adapt_authoring/issues/2313
=> Updated 'menu' value

README.md, bower.json, js/adapt-contrib-boxMenu.js
[#2776](https://github.com/adaptlearning/adapt_framework/issues/2776)
* Registered the menu view and model accordingly
* Bumped framework dependency to 5.5+
=> issue/2776 Added multi-menu support

bower.json, js/adapt-contrib-boxMenu.js
[#2940](https://github.com/adaptlearning/adapt_framework/issues/2940)
* Switched new [boxMenu groups behaviour](https://github.com/adaptlearning/adapt-contrib-boxMenu/commit/0157139eff5f326757661ead329b4b8619548731) to new [childViews API](https://github.com/adaptlearning/adapt_framework/commit/c36300cb486e68ae727886488f7a03f3821e3761)
=> issue/2940 Switch to new childViews API

README.md
Resolves https://github.com/adaptlearning/adapt_framework/issues/2955
* Removed accessibility section
* Added durationLabel to course globals
=> readMe updates

bower.json, schema/contentobject.schema.json, schema/course.schema.json
Part of https://github.com/adaptlearning/adapt_framework/issues/2704.
=> Add support for authoring tool 1

js/BoxMenuGroupView.js
Fixes #104 
Fixing template name typo
=> issue/104 Fix template name typo

js/BoxMenuItemView.js
Resolves https://github.com/adaptlearning/adapt-contrib-boxMenu/issues/106
* boxMenuItemView inherit menuItemView class states
=> BoxMenuItemView inherit menuItemView classes

js/BoxMenuGroupView.js
Resolves https://github.com/adaptlearning/adapt-contrib-boxMenu/issues/109
* boxMenuGroupView inherit menuItemView class states
=> BoxMenuGroupView inherit menuItemView classes

js/BoxMenuView.js
fixes #114 
* Inherit classes from [MenuView](https://github.com/adaptlearning/adapt-contrib-core/blob/a9dfe63d8066a459b993028df3a261fa6c8f21fd/js/views/menuView.js#L4) and [ContentObjectView](https://github.com/adaptlearning/adapt-contrib-core/blob/a9dfe63d8066a459b993028df3a261fa6c8f21fd/js/views/contentObjectView.js#L15-L26) accordingly
=> issue/114 Corrected class inheritance

js/BoxMenuView.js
fixes https://github.com/adaptlearning/adapt-contrib-vanilla/issues/342
fixes https://github.com/cgkineo/adapt-visua11y/issues/38
* Move header and menu backgrounds to separate layers
requires https://github.com/adaptlearning/adapt-contrib-vanilla/pull/334
=> issue/38 Moved backgrounds into separate divs

js/adapt-contrib-boxMenu.js, package.json
fixes #124 
* Switched from `Adapt.register` to `components.register`
=> Fix: Remove deprecated behaviour (fixes #124)

package.json, templates/boxMenu.hbs, templates/boxMenuGroup.hbs, templates/boxMenuItem.hbs
fixes https://github.com/adaptlearning/adapt-contrib-core/issues/235
* Ensure support for new unified headings
Requires https://github.com/adaptlearning/adapt-contrib-core/pull/247
=> Fix: Ensure menu is compatible with clickable headings in core

README.md, example.json, js/BoxMenuView.js, less/boxMenu.less, properties.schema, schema/course.schema.json
Fixes: #128 
* Added new text alignment property to menu header. Allows users to align title, body, or instruction elements to the left, center, or right.
=> New: Text alignment update (fixes #128)

less/boxMenu.less, less/boxMenuGroup.less, package.json
Fixes: #130 
* Changed `@max-width` to `@max-page-width`
* Changed `@device-width-large` to `@max-content-width`
Dependencies
* Core [pull 275](https://github.com/adaptlearning/adapt-contrib-core/pull/275)
* Vanilla [pull 380](https://github.com/adaptlearning/adapt-contrib-vanilla/pull/380)
* LanguagePicker [pull 76](https://github.com/adaptlearning/adapt-contrib-languagePicker/pull/76)
=> Update: Control content max width via variable (fixes #130)

less/boxMenuItem.less, templates/boxMenuItem.hbs
* Adds menu lock indicator to solve for #134 
[//]: # (List appropriate steps for testing if needed)
1. Install this PR 
2. Also grab adapt-contrib-theme update for styling: https://github.com/adaptlearning/adapt-contrib-vanilla/pull/390
[//]: # (Mention any other dependencies)
You must also use the PR from adapt-contrib-theme: https://github.com/adaptlearning/adapt-contrib-vanilla/pull/390
=> New: Adds locking icon to locked menu items (fixes: #134)

templates/boxMenuItem.hbs
* Fixes #138  
[//]: # (List appropriate steps for testing if needed)
1. Pull down this PR and examine the structure in the output
[//]: # (Mention any other dependencies)
=> Fix: Normalizing template icons (fixes: #138)

js/BoxMenuView.js, templates/boxMenuItem.hbs
Fixes #140 #132 
* Standardise aria-labels with recent changes to component aria labels
[//]: # (Mention any other dependencies)
=> Fix: Standardise aria-label with updated component aria-label

schema/course.schema.json
Fixes (#144)
* Nests globals schema within an _menu object (fixes #144)
=> Fix: _globals schema nesting (fixes #144)

templates/boxMenu.hbs
Fixes #148 
* Changed template to use pageBody if available
=> Added pageBody attribute

js/BoxMenuGroupView.js, js/BoxMenuView.js
#164 
* Exclude hidden items from items count ARIA (fixes #164)
=> Fix: Exclude hidden items from items count ARIA (fixes #164)

test/e2e/adapt-contrib-boxMenu.cy.js
Fixes #174 
* Texts were failing due to 'this' context
=> Fix: Fixing context calls (174)

js/BoxMenuView.js
fixes #185 
* Change from Adapt.device to device directly
=> Fix: Change from Adapt.device to device directly

less/boxMenuItem.less
Fixes #189 
* Complete icon added to the status element.
=> New: Complete icon styling added (fixes #189)

.github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/issue_template.md
Fixes https://github.com/adaptlearning/adapt-contrib-boxMenu/issues/207
* Add new `issue_template.md` file with YAML frontmatter
* Add new `config.yml` file to disable blank template
=> Chore: Add support for new issue experience (fixes #207)

bower.json, package-lock.json, package.json
#220 
Part of - https://github.com/adaptlearning/adapt_framework/issues/3698
* package updated to include semantic-release-replace-plugin for automated migration versioning (fixes #220)
=> Update: package updated to include semantic-release-replace-plugin for automated migration versioning (fixes #220)
