adaptlearning/adapt-contrib-boxMenu

example.json, templates/boxmenu-item.hbs
It was obviously missed that any text displayed should be externalised into JSON files, I've pulled out the "Duration:" label into `durationLabel` property.
{
"_id":"co-01",
"_parentId":"course",
"_type":"page",
"linkText":"View",
"durationLabel":"Duration:",
"duration":"5 mins"
},
=> Lukasz Grela - externalise "Duration" into durationLabel JSON property

templates/boxmenu.hbs
- one selector can be used to style rather than selecting title and body separately.
- offers more flexibility when styling - separate menu content, set backgrounds/widths - I find myself constantly adding this in on project work.
=> Title and body wrapped in header element

js/adapt-contrib-boxmenu.js
The menu was resetting it's own completion if any _isOptional components existed by weren't complete.
* Use model completion calculation to include _isOptionals etc for standard behaviour
Should be checked with:
https://github.com/adaptlearning/adapt-contrib-assessment/pull/45
https://github.com/adaptlearning/adapt_framework/pull/659
https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/pull/54
=> ABU-710: Fixed menu completion calculation to use model

templates/boxmenu-item.hbs
I believe we shouldn't have "else" in the following line of code: https://github.com/adaptlearning/adapt-contrib-boxmenu/blob/master/templates/boxmenu-item.hbs#L16 , if a user doesn't want to specify the durationLable then it should be empty, and if the language is not English, then they will be forced to have the word "duration" in a different language course.
=> Remove hard coded "Duration:"

templates/boxmenu-item.hbs
[#2158](https://github.com/adaptlearning/adapt_framework/issues/2158)
* Allowed image to read after heading as this make more sense when using a screen reader
List of outstanding PRs: https://github.com/adaptlearning/adapt_framework/issues/2206.
=> accessibility: issue/#2158 moved image to read out after heading

js/adapt-contrib-boxmenu.js, properties.schema, templates/boxmenu-item.hbs, templates/boxmenu.hbs
[#2075](https://github.com/adaptlearning/adapt_framework/issues/2075)
* Removed a11y_text
* Removed unnecessary tabindex
[#2083](https://github.com/adaptlearning/adapt_framework/issues/2083)
* Added heading completion statuses
[#2084](https://github.com/adaptlearning/adapt_framework/issues/2084)
* Removed component description
[#2118](https://github.com/adaptlearning/adapt_framework/issues/2118);
*  Added list roles
[#2119](https://github.com/adaptlearning/adapt_framework/issues/2119)
* Moved duration label and progress indicator
General
* Switch at `a11y_aria_label`
List of outstanding PRs: https://github.com/adaptlearning/adapt_framework/issues/2206.
=> accessibility: fixes issue/#2075 issue/#2084 issue/#2084 issue/#2118 issue/#2119

templates/boxMenuItem.hbs
it's not needed by the a11y functionality any more (in fact this is the only reference to it I can find in Adapt v5)
=> remove class accessible-text-block

README.md, example.json
=> remove placeholder alt text from example

templates/boxMenuItem.hbs
Resolves https://github.com/adaptlearning/adapt-contrib-boxMenu/issues/108
* Replaced `disabled='disabled'` with `aria-disabled='true'` on button so it remains in keyboard navigation 
* Added item number 
* Changed linkText to page title
* Added optional and completed aria states (optional isn't in FW yet but added support)
=> Aria improvements to menu item button

README.md, example.json, less/boxMenu.less, properties.schema, schema/course.schema.json, templates/boxMenu.hbs
Fixes #133 
* Add a new `_graphic` object that can be used to add an image (ex. a logo) above the menu title.
1. In `course.json`, add the following:
```
"_boxmenu": {
"_graphic": {
"alt": "Logo",
"_src": "course/en/images/logo.png"
}
},
``` 
2. Ensure that the image appears above the menu title.
3. Ensure that either the alt text or aria-hidden="true" is included on the image.
=> Fix: Add option to add a graphic to the menu header (fixes #133)

properties.schema, schema/course.schema.json
Added schema updates for Extra large breakpoint already added to core. 
Ref: https://github.com/adaptlearning/adapt-contrib-core/issues/362
=> Fix: added schema for xlarge breakpoint 

properties.schema, schema/course.schema.json, templates/boxMenuItem.hbs
Fixes #151 
* Adds new property `itemCount` with a default value of `Item {{_nthChild}} of {{_totalChild}}`
* Adjustments to space characters in button aria-label so that it doesn't start with a space.
=> Fix: Button aria contains text not accessible for translations (fixes #151)

js/BoxMenuGroupView.js
Fixes https://github.com/adaptlearning/adapt-contrib-boxMenu/issues/160
Item count is relevant to it's parent container (all items within Boxmenu as default, or items contained within a parent group).
**Test PR**
Configure your course to use the  Boxmenu grouping (see [example](https://github.com/adaptlearning/adapt-contrib-boxMenu/blob/1139ecbaf778365ef467f93117d93879bdba6884/example.json#L59) for ref).
Inspect 'View' Button `aria-label` and item count should be relevant to the Boxmenu group set up. 
e.g.  item index in group +  total items in group
=> Fix: Update item count ARIA for grouped items (fixes #160)

templates/boxMenu.hbs
Fixes: #166 
* Added new content container element to menu template
=> Update: Added content container element (fixes #166)

test/e2e/adapt-contrib-boxMenu.cy.js
addresses adaptlearning/adapt-contrib-boxMenu#167
=> Chore: Added menu page e2e tests (Issue/167)

test/e2e/adapt-contrib-boxMenu.cy.js
Addresses #176 
* Using testContainsOrNotExists helper function and tidy up of getData call
=> Chore: Using testContainsOrNotExists helper function and tidy up of getData call

test/e2e/adapt-contrib-boxMenu.cy.js
Fixes: #178
* Check landing page is a boxmenu type menu
=> Fix: Check landing page is a boxmenu type menu

templates/boxMenuItem.hbs
Fixes https://github.com/adaptlearning/adapt-contrib-boxMenu/issues/182
As per [Vanilla issue #446](https://github.com/adaptlearning/adapt-contrib-vanilla/issues/446), disabled locked buttons should have [_globals._accessibility._ariaLabels.locked](https://github.com/adaptlearning/adapt_framework/blob/c85bb887354dc07a44fb6e61779be584d81ede4a/src/course/en/course.json#L64) prepended to the button ARIA.
Set `_lockType` in _course.json_, for example `"_lockType": "lockLast"`.
Locked menu items should have 'Locked' prepended to the button `aria-label` in place of the `linkText` 'View' text.
e.g. Locked. Adapt Assessment. Item 3 of 3.
When unlocked, button `aria-label` resumes `linkText`.
e.g. View Adapt Assessment. Item 3 of 3.
=> Update: prepend locked ARIA to item button (fixes #182)

README.md, example.json
Fixes #184 
* Adds `_xlarge` property to _README.md_ and _example.json_
=> Fix: Add xlarge props to documentation (fixes #184)

js/BoxMenuView.js, templates/boxMenu.jsx
fixes #195 
* Allow for missing configs
=> Fix: Guards for missing configs (fixes #195)

templates/boxMenuItem.jsx
Fixes https://github.com/adaptlearning/adapt-contrib-boxMenu/issues/198
* Use image template for consistency with other plugin images and multi device support.
* Support for device breakpoint sizes: `small`, `medium`, `large` and `xlarge`.
* When **only** `small` and `large` images are defined, images switch from `small` to `large` at `medium` (for separate mobile and desktop images).
**Note, this development is only available to the Framework at present until a core _contentobject.model.schema_ file is updated to offer up the flexibility to the AAT. This is also the case for all other plugins that use the image template.**
Please test the following use cases. All code snippets reference pre-bundled course images.
1. Default support for src
```
"_graphic": {
"src": …
```
=> New: support for responsive menu item image sources (fixes #198)

schema/course.schema.json
#204 
* isObjectId removed from schema to allow external assets to be added (fixes #204)
=> Fix: isObjectId removed from schema to allow external assets to be added (fixes #204)

bower.json, js/BoxMenuModel.js, package.json
fixes #212 
requires https://github.com/adaptlearning/adapt-contrib-core/pull/645
* Allow core router to treat a group as a sub-part of the parent contentobject rather than as a main contentobject
=> Fix: Make _renderAsGroup as typegroup=group (fixes #212)
